version: "3.8"

services:
    db_mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Parola1!strong
            MSSQL_PID: Express
        volumes:
            - db-volume:/var/opt/mssql
        ports:
            - 1433:1433
        networks:
            - bl_db

    blogforpeace:
        image: elrego1/blog_for_peace:latest
        deploy:
            mode: replicated
            replicas: 2
            placement:
                max_replicas_per_node: 3
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        ports:
            - "80:80"
            - "7152:7152"
        networks:
            - bl_db

    mosquitto:
        image: elrego1/blog_for_peace_mqtt:latest
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: stop-first
            rollback_config:
                parallelism: 1
                order: stop-first
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - bl_mqtt
            - proxy_mqtt

    # mariadb_nginx-proxy-manager:
    #     image: jc21/mariadb-aria:latest
    #     environment:
    #         - PUID=911
    #         - PGID=911
    #         - MYSQL_ROOT_PASSWORD=adminadmin
    #         - MYSQL_DATABASE=nginx-proxy-manager
    #         - MYSQL_USER=nginx-proxy-manager
    #         - MYSQL_PASSWORD=proxyadmin
    #     volumes:
    #         - mariadb_nginx-proxy-manager_db:/var/lib/mysql

    # nginx-proxy-manager:
    #     image: jc21/nginx-proxy-manager:latest
    #     environment:
    #         # These are the settings to access your db
    #         DB_MYSQL_HOST: "mariadb_nginx-proxy-manager"
    #         DB_MYSQL_PORT: 3306
    #         DB_MYSQL_NAME: "nginx-proxy-manager"
    #         DB_MYSQL_USER: "nginx-proxy-manager"
    #         DB_MYSQL_PASSWORD: "proxyadmin"
    #     volumes:
    #         - nginx-proxy-manager_data:/data
    #         - nginx-proxy-manager_letsencrypt:/etc/letsencrypt
    #     ports:
    #         # Public HTTP Port:
    #         - '80:80'
    #         # Public HTTPS Port:
    #         - '443:443'
    #         # Admin Web Port:
    #         - '81:81'


volumes:
    db-volume:
    mosquitto_data:
    mosquitto_log:

    mariadb_nginx-proxy-manager_db:

    nginx-proxy-manager_data:
    nginx-proxy-manager_letsencrypt:

networks:
    proxy_bl:
    proxy_mqtt:
    bl_mqtt:
    bl_db:
    agent_network:
        driver: overlay
        attachable: true
