version: "3.8"

services:
    db_mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Parola1!strong
            MSSQL_PID: Express
        volumes:
            - db-volume:/var/opt/mssql
        networks:
            - bl_db

    blogforpeace:
        image: elrego1/blog_for_peace:latest
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 1
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        networks:
            - bl_db
            - bl_mqtt
            - proxy_bl

    mosquitto:
        image: elrego1/blog_for_peace_mqtt:latest
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: stop-first
            rollback_config:
                parallelism: 1
                order: stop-first
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - bl_mqtt

volumes:
    db-volume:
    mosquitto_data:
    mosquitto_log:

    mariadb_nginx-proxy-manager_db:

    nginx-proxy-manager_data:
    nginx-proxy-manager_letsencrypt:

networks:
    proxy_proxy-db:

    proxy_bl:

    bl_mqtt:
    bl_db:
