name: MQTT

on:
  push:
    branches: [ idp_dev, production ]
  pull_request:
    branches: [ idp_dev, production ]

jobs:
  docker:
    name: Build image & Publish on Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: elrego1/blog_for_peace_mqtt
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
              -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t elrego1/blog_for_peace_mqtt:latest -t elrego1/blog_for_peace_mqtt:${GITHUB_SHA::8} -f ./Dockerfile-app .
      - name: Publish Docker image
        run: docker push $REPO
