version: "3.8"

services:
    db_mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Parola1!strong
            MSSQL_PID: Express
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        volumes:
            - db-volume:/var/opt/mssql
        ports:
            - 1433:1433
        networks:
            - bl_db

    blogforpeace:
        image: elrego1/blog_for_peace:latest
        deploy:
            mode: replicated
            replicas: 2
            placement:
                max_replicas_per_node: 3
            update_config:
                parallelism: 1
                order: start-first
            rollback_config:
                parallelism: 1
                order: start-first
        ports:
            - "80:80"
            - "7152:7152"
        networks:
            - bl_db

    mosquitto:
        image: elrego1/blog_for_peace_mqtt:latest
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: stop-first
            rollback_config:
                parallelism: 1
                order: stop-first
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        networks:
            - bl_mqtt
            - proxy_mqtt

volumes:
    db-volume:
    mosquitto_data:
    mosquitto_log:

networks:
    proxy_bl:
    proxy_mqtt:
    bl_mqtt:
    bl_db:
    agent_network:
        driver: overlay
        attachable: true
